POST http://localhost:8080/api/productos/guardar HTTP/1.1
content-type: application/json

{
    "title": "Samsung 970 EVO Plus MZ-V7S2T0 2TB",
    "price": 79709,
    "thumbnail": "https://cdn-icons-png.flaticon.com/512/2004/2004748.png"
}

###

POST http://localhost:8080/api/productos/guardar HTTP/1.1
content-type: application/json

{
    "title": "JORDAN AIR 5 RETRO",
    "price": 35999,
    "thumbnail": "https://t3.ftcdn.net/jpg/01/67/74/24/240_F_167742407_3qY083CZfrfOQCN3JFMae2u0hQU2aNhU.jpg"
}

###

POST http://localhost:8080/api/productos/guardar HTTP/1.1
content-type: application/json

{
    "title": "ADIDAS FORUM LOW",
    "price": 12999,
    "thumbnail": "https://cdn-icons-png.flaticon.com/512/732/732160.png"
}


###

GET  http://localhost:8080/api/productos/listar HTTP/1.1
